name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Automatic Releases
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@526ce12c6675bbe6e0e9a4169c90d09a3f7ad3e2
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          # GitHub secret token
          repo_token: AUTO_RELEASE # i dont know how this works
          # Git tag (for automatic releases)
          automatic_release_tag: true
          # Should this release be marked as a draft?
          draft: false
          # Should this release be marked as a pre-release?
          prerelease: true
