name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: 'true'
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: alchemy.${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          repo_token: '${{ secrets.AUTO_RELEASE }}'
          automatic_release_tag: 'auto-release'
          title: 'Automatic Release'
          files: |
            *.zip
