name: Build Godot Project

on:
  #push: {}
  #pull_request: {}
  workflow_dispatch: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [x86_64, exe, dmg]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: alchemy
          preset: ${{ matrix.platform }}
          debugMode: 'false'
      - name: Upload Artifact
        id: artifact
        uses: actions/upload-artifact@v2
        with:
          name: alchemy.${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Automatic Releases
        id: release
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          repo_token: ${{ secrets.AUTO_RELEASE }}
          automatic_release_tag: 'master'
          title: 'Automatic Release'
          files: |
            ${{ steps.release.outputs.artifact }}
