name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Sentry Release
      # You may pin to the exact commit or the version.
      # uses: getsentry/action-release@641a80f3e05619b174bcacbfa3b69dff382d2a33
        uses: getsentry/action-release@v1.1.5
        with:
          finalize: false
